version: "3"
containers:
- name: container
  #image: fedora
  image: centos
  shell: /bin/bash
virtualmachines:
- name: crc
#  image: openshift-instruqt/openshift-instruqt-crc490-211026
  image: rhd-devx-instruqt/openshift-4-11-7-lgph7
  machine_type: n1-standard-16
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: spoke1
  image: instruqt/k3s-v1-24-4
  shell: /bin/bash
  environment:
    K3S_TOKEN: superSecur3T0ken
  machine_type: n1-standard-4
- name: spoke2
  image: instruqt/k3s-v1-24-4
  shell: /bin/bash
  environment:
    K3S_TOKEN: superSecur3T0ken
  machine_type: n1-standard-4   
