#!/bin/bash

# Instruqt runs cleanup and setup scripts in parallel. 
# These tasks have moved to the next challenge setup so blocking call are respected.
# https://instruqt.slack.com/archives/CLGDKB0UU/p1657624989180079
