#!/bin/bash
set -x

# Clean up previous challenge.
PROJECT_PATH="/root/team-pacman"
rm -rf $PROJECT_PATH

oc delete namespace team-pacman --wait=true

# Challenge setup

oc new-project team-pacman


PROJECT_PATH="/root/team-pacman"
mkdir -p $PROJECT_PATH

curl -o $PROJECT_PATH/mongo-deployment.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/03-persistent-volume-claim/content/mongo-deployment.yml"
oc apply -f $PROJECT_PATH/mongo-deployment.yml

curl -o $PROJECT_PATH/mongo-service.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/03-persistent-volume-claim/content/mongo-service.yml"
oc apply -f $PROJECT_PATH/mongo-service.yml

curl -o $PROJECT_PATH/mongo-pvc.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/03-persistent-volume-claim/content/mongo-pvc.yml"
# don't apply mongo-pvc, let the student create it via the console

curl -o $PROJECT_PATH/pacman-deployment.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/03-persistent-volume-claim/content/pacman-deployment.yml"
oc apply -f $PROJECT_PATH/pacman-deployment.yml

curl -o $PROJECT_PATH/pacman-route.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/03-persistent-volume-claim/content/pacman-route.yml"
oc apply -f $PROJECT_PATH/pacman-route.yml

curl -o $PROJECT_PATH/pacman-service.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/03-persistent-volume-claim/content/pacman-service.yml"
oc apply -f $PROJECT_PATH/pacman-service.yml
