#!/bin/bash

# Challenge setup

PROJECT_PATH="/root/team-pacman"
mkdir -p $PROJECT_PATH

curl -o $PROJECT_PATH/mongo-deployment.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/${INSTRUQT_CHALLENGE_ID}/content/mongo-deployment.yml"


curl -o $PROJECT_PATH/mongo-service.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/${INSTRUQT_CHALLENGE_ID}/content/mongo-service.yml"


curl -o $PROJECT_PATH/mongo-pvc.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/${INSTRUQT_CHALLENGE_ID}/content/mongo-pvc.yml"


curl -o $PROJECT_PATH/pacman-deployment.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/${INSTRUQT_CHALLENGE_ID}/content/pacman-deployment.yml"


curl -o $PROJECT_PATH/pacman-route.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/${INSTRUQT_CHALLENGE_ID}/content/pacman-route.yml"


curl -o $PROJECT_PATH/pacman-service.yml \
  "https://raw.githubusercontent.com/lijcam/Instruqt/main/kubernetes-fundamentals/${INSTRUQT_CHALLENGE_ID}/content/pacman-service.yml"

