#!/bin/sh

ENVIRONMENT_VAR_SET=$(oc get deployment crash-test -o jsonpath='{.spec.template.spec.containers[?(@.name=="crash-test")].env[?(@.name=="LOG_ECHO")]}')

[[ -n "${ENVIRONMENT_VAR_SET}" ]] && true || false
