#!/bin/sh

ENVIRONMENT_VAR_SET=$(oc get deployment crash -o jsonpath='{.spec.template.spec.containers[?(@.name=="crash")].env[?(@.name=="LOG_ECHO")]}')

[[ -z "${ENVIRONMENT_VAR_SET}" ]] && true || false
