#!/bin/sh

oc new-project crash-test

cat << EOF | oc apply -n crash-test -f -
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: crash-test
  labels:
    app: crash-test
    app.kubernetes.io/component: crash-test
    app.kubernetes.io/instance: crash-test
    app.kubernetes.io/name: crash-test
    app.kubernetes.io/part-of: crash-test
    app.openshift.io/runtime: crash-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-test
  template:
    metadata:
      labels:
        app: crash-test 
    spec:
      containers:
      - image: quay.io/lijcam/crash:v1
        name: crash-test
EOF
