version: "3"
containers:
- name: container
  image: fedora
  shell: /bin/bash
virtualmachines:
- name: crc
  image: openshift-instruqt/openshift-instruqt-crc490-211026
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: spoke1
  image: instruqt/k3s-v1-25-0
  shell: /bin/bash
  environment:
    K3S_TOKEN: superSecur3T0ken
  machine_type: n1-standard-1
- name: spoke2
  image: instruqt/k3s-v1-25-0
  shell: /bin/bash
  environment:
    K3S_TOKEN: superSecur3T0ken
  machine_type: n1-standard-1    